import { ApolloClient, InMemoryCache } from "@apollo/client";
import Head from "next/head";
import { GET_ALL_PRODUCTS } from "../api/queries";
import Products from "../components/products";
import styles from "../styles/Home.module.css";

export default function Home({ products }) {
  console.log(products);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Products />
      </main>

      <footer></footer>
    </div>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: process.env.WP_GRAPHQL_API,
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: GET_ALL_PRODUCTS,
  });

  return {
    props: {
      products: data.products.nodes,
    },
  };
}
